### ISSUE TITLE
Add possibility to delete previous tests

### ISSUE THREAD

**Issue by ohlr** [letsdebug/letsdebug#22]
I find letsdebug a very helpful tool.

However, it would be great if previous tests do not get listed in search-engines.

There should be a possibility to delete a previous test or to add them to the `robots.txt`

**Comment by alexzorin** [comment]
I agree, search engines indexing the test results is very undesirable.

All results and result lists are now disallowed by robots.txt.

Deletion is more complicated because we don't want random users deleting tests results not belonging to them. I'm not opposed to it, but it requires some extra thought.

**Comment by ohlr** [comment]
Thanks for the fast action.
Maybe a little checkbox that asks before running a test if the result should be auto-deleted after one day or so could solve it?

**Comment by ohlr** [comment]
The page is still on google.

I believe that is due to your robots.txt - Since you disallow crawling the relevant pages.. Google can not find the noindex meta tag

**Comment by alexzorin** [comment]
Yep ... that was pretty dumb.

**Comment by alexzorin** [comment]
From what I can tell, DuckDuckGo and Google have almost entirely deindexed the existing result listings. There's a handful of stragglers left, but I assume those are just a matter of time.

I don't feel convinced that explicit deletion of results is warranted or worthwhile, since anybody can submit a test for any domain. Going to close as I think this is (finally) fixed.

**Comment by CodeAlDente** [comment]
> [...] I don't feel convinced that explicit deletion of results is warranted or worthwhile, since anybody can submit a test for any domain. [...]

Why don't we just check if there's already a report for a domain and redirect to it? And if it's too old, the check can be run again. That would avoid duplicates and improve stability and reliability as reports will not be run that often as everybody is using the same resource. And to free space for reports that are no longer needed they could be deleted after a month or so since the last time they have been viewed?

**Comment by alexzorin** [comment]
I appreciate the thoughts, but I don't want to change anything in those respects.

>And to free space for reports that are no longer needed they could be deleted after a month or so since the last time they have been viewed

Longevity of the reports is important to me as they provide context in forum threads, where another reader may stumble upon the same problem after months or years.

The 115,866 test results so far take a measly 231MB on disk, so we're pretty much good for the next ~500 years.

>check if there's already a report for a domain

There are potential complications here. If two users are testing one domain, and one of the users is the server admin who has just made a configuration change, that is a recipe for confusion because the test that finished 30 seconds ago may not have seen that configuration change.

I don't want to deduplicate in-flight tests either, because sometimes tests can take 30 minutes to run (nameserver timeouts), and I don't want to prevent new tests just because one test is stalled.

I know (by way of benchmark) that the tool can deal with a relatively high volume of concurrent tests, and I've almost never seen it go above 1 test at a time, let alone 2.
